### PR TITLE
Remove self.locations

### PR DESCRIPTION
**Pull request by lenwar**
remove self.locations. They are no longer referenced. Code works fine under current version of Hassio and Smile P1 V2 after these changes.

### CODE REVIEW

**Comment by bouwew** [comment]
Ok, done, thanks!

**Comment by bouwew** [comment]
Hi @lenwar we (@CoMPaTech and I) are trying to create one custom_component that covers most of the Plugwise devices: the Anna's, the Smile P1 v2 and v3 and the Adam.
You have a Smile P1 v2, are you willing to help us by testing our new code?

**Comment by lenwar** [comment]
Hi,

Sure thing. Always happy to help.

FYI: I am a Linux engineer at an international financial company. I can read most code, do some modifications, but I'm not a programmer. (just so you know at what level you can communicate with me :-) )


Kind regards,
Lennard

29 mrt. 2020 20:05:07 Bouwe Westerdijk <notifications@github.com>:

**Comment by CoMPaTech** [comment]
Long time Unix/Linux engineer here as well. Considering myself to be more of a functional scripter than a programmer but committing upstream increases ones skills tremendously (it did for me!). 

We have the new custom component at https://github.com/plugwise/plugwise-beta - if you have HACS running you can even add that as a custom repo to HACS and deploy without touching the command line :) Otherwise just download a release or clone it for master and copy it over to `custom_components`.

I'd love to hear if it 'does anything' for your P1, just before starting out with it, if you look at line 326 of [Travis for  build 109](https://travis-ci.org/github/plugwise/Plugwise-Smile/builds/668437151) you'll see the output that it currently is generating. I'm expecting some issues in that data, but it might be more helpful if someone with actual data can compare it.

The `net_electricity.*` things are injected calculations of netto usage to cope with solar panel data. It worked great for a P1v3 user, not sure about the data on a v2 yet.

**Comment by bouwew** [comment]
@lenwar Make sure to disable the present Smile P1 custom_component first and restart HA before you install the plugwise-beta component.

**Comment by lenwar** [comment]
Hi,

I did an install via HACS and I'm receiving data.
I'm reading:
- Current power usage - electricity_consumed_peak_point
- Cumulative power usage (high) - sensor.smile_p1_electricity_consumed_peak_cumulative
- Cumulative power usage (high) - sensor.smile_p1_net_electricity_cumulative
- Current power production - sensor.smile_p1_electricity_produced_peak_point (I'm not producing anything)
- Cumulative power produced - sensor.smile_p1_electricity_produced_peak_cumulative
- Effective power usage? (usage - production I guess?) - net_electricity_point

So I'm getting two values, which are the same (incorrect). I'm also not getting any gas values.

**Comment by CoMPaTech** [comment]
See above issue

**Comment by bouwew** [comment]
@lenwar Can you please capture the XML-data from your Smile P1? The output of `http://{ip}/core/domain_objects` ? Please save it as an XML-file.

Note that solar or not, the sensors will always be present, just ... they should remain at 0. For gas it should have worked, but lets see whats up if you have the xml.

**Comment by lenwar** [comment]
I added it to https://github.com/plugwise/plugwise-beta/issues/2

**Comment by bouwew** [comment]
Thanks!

**Pull request merged**
